/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.riwicodeup.ui;

import com.mycompany.riwicodeup.db.EstudianteDAO;
import com.mycompany.riwicodeup.domain.Estudiante;
import com.mycompany.riwicodeup.domain.Nota;
import com.mycompany.riwicodeup.service.ArchivoService;
import com.mycompany.riwicodeup.service.CalculoService;
import com.mycompany.riwicodeup.service.RegistroEstudianteService;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import javax.swing.JOptionPane;

/**
 *
 * @author Coder
 */
public class RegistroEstudianteFrame extends javax.swing.JFrame {

    int filaSeleccionada;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroEstudianteFrame.class.getName());

    /**
     * Creates new form RegistroEstudianteFrame
     */
    public RegistroEstudianteFrame() throws SQLException {
        initComponents();
        tableEstudiantes.getColumnModel().getColumn(1).setPreferredWidth(200);
        tableEstudiantes.getColumnModel().getColumn(0).setPreferredWidth(80);
        for (int i = 2; i < tableEstudiantes.getColumnCount(); i++) {
            tableEstudiantes.getColumnModel().getColumn(i).setPreferredWidth(80); // Otras más pequeñas
        }
        setLocationRelativeTo(null);
        actualizarListaEstudiantes();
    }

    private void actualizarListaEstudiantes() throws SQLException {
        var modelo = (javax.swing.table.DefaultTableModel) tableEstudiantes.getModel();
        modelo.setRowCount(0); // Limpia la tabla
        for (var est : RegistroEstudianteService.listarEstudiantes()) {
            modelo.addRow(new Object[]{
                est.getId(),
                est.getNombre(),
                est.getEdad(),
                est.getNotas().get(0).getValor(),
                est.getNotas().get(1).getValor(),
                est.getNotas().get(2).getValor()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNota1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNota2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNota3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEstudiantes = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnEstadistica = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnGuardarCSV = new javax.swing.JButton();
        btnCargarCSV = new javax.swing.JButton();
        lblEstadistica = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Edad");

        jLabel3.setText("Nota 1");

        jLabel4.setText("Nota 2");

        jLabel5.setText("Nota 3");

        tableEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nombre", "Edad", "Nota 1", "Nota 2", "Nota 3"
            }
        ));
        tableEstudiantes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableEstudiantes.setShowGrid(true);
        tableEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEstudiantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEstudiantes);

        btnGuardar.setBackground(new java.awt.Color(51, 153, 0));
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEstadistica.setBackground(new java.awt.Color(204, 204, 204));
        btnEstadistica.setForeground(new java.awt.Color(0, 0, 0));
        btnEstadistica.setText("Estadistica");
        btnEstadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticaActionPerformed(evt);
            }
        });

        btnCalcular.setBackground(new java.awt.Color(153, 153, 0));
        btnCalcular.setForeground(new java.awt.Color(0, 0, 0));
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(153, 0, 0));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Log out");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnGuardarCSV.setBackground(new java.awt.Color(204, 255, 204));
        btnGuardarCSV.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardarCSV.setText("Guardar CSV");
        btnGuardarCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCSVActionPerformed(evt);
            }
        });

        btnCargarCSV.setBackground(new java.awt.Color(204, 255, 204));
        btnCargarCSV.setForeground(new java.awt.Color(0, 0, 0));
        btnCargarCSV.setText("Cargar CSV");
        btnCargarCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarCSVActionPerformed(evt);
            }
        });

        lblEstadistica.setForeground(new java.awt.Color(51, 102, 255));
        lblEstadistica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel6.setText("Estadistica Estudiante");

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(0, 153, 255));
        btnActualizar.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalir)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(btnCalcular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEstadistica))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtNombre)
                                    .addComponent(jLabel5)
                                    .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(txtNota1)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNota3))))
                        .addGap(53, 53, 53)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCargarCSV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarCSV)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(148, 148, 148))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblEstadistica, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCalcular, btnEstadistica});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCargarCSV, btnGuardarCSV});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtEdad, txtNombre, txtNota1, txtNota2, txtNota3});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnActualizar, btnEliminar, btnGuardar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(4, 4, 4)
                        .addComponent(txtNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCargarCSV)
                            .addComponent(btnGuardarCSV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstadistica, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnEliminar)
                            .addComponent(btnActualizar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEstadistica)
                            .addComponent(btnCalcular))))
                .addGap(16, 16, 16))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnActualizar, btnCalcular, btnCargarCSV, btnEliminar, btnEstadistica, btnGuardar, btnGuardarCSV});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private List<Nota> obtenerNotasDesdeCampos() {
        List<Nota> notas = new ArrayList<>();

        try {
            double valor1 = Double.parseDouble(txtNota1.getText());
            double valor2 = Double.parseDouble(txtNota2.getText());
            double valor3 = Double.parseDouble(txtNota3.getText());

            notas.add(new Nota(valor1));
            notas.add(new Nota(valor2));
            notas.add(new Nota(valor3));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Todas las notas deben ser números válidos.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        return notas;
    }

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
            String nombre = txtNombre.getText();
            int edad = Integer.parseInt(txtEdad.getText());

            if (nombre.isBlank()) {
                throw new IllegalArgumentException("El nombre es obligatorio.");
            }

            if (edad <= 0) {
                throw new IllegalArgumentException("La edad debe ser un numero positivo");
            }

            List<Nota> notas = obtenerNotasDesdeCampos();

            Estudiante estudiante = new Estudiante(UUID.randomUUID().toString(), nombre, edad, notas);
            RegistroEstudianteService registroService = new RegistroEstudianteService();
            registroService.agregarEstudiante(estudiante);
            actualizarListaEstudiantes();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Edad y notas deben ser números válidos.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de validación", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "¿Estas seguro de cerrar la sesion?", "Salir", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            var frame = new Login();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCSVActionPerformed
        try {
            // TODO add your handling code here:
            ArchivoService.guardarCSV(this, tableEstudiantes);
        } catch (SQLException ex) {
            System.getLogger(RegistroEstudianteFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnGuardarCSVActionPerformed

    private void btnCargarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarCSVActionPerformed
        // TODO add your handling code here:
        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Desea reemplazar la lista actual?", "Confirmar", JOptionPane.YES_NO_OPTION);
        boolean reemplazar = (confirmacion == JOptionPane.YES_OPTION);

        ArchivoService.cargarCSV(this, reemplazar);
        try {
            actualizarListaEstudiantes();
        } catch (SQLException ex) {
            System.getLogger(RegistroEstudianteFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnCargarCSVActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombre.getText();
        int edad = Integer.parseInt(txtEdad.getText());
        List<Nota> notas = obtenerNotasDesdeCampos();

// Validación básica
        if (nombre.isEmpty() || notas.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios.");
            return;
        }

// Crear estudiante temporal
        Estudiante estudiante = new Estudiante("TEMP", nombre, edad, notas);

// Calcular
        double promedio = CalculoService.promedio(estudiante.getNotas());
        Nota notaMax = CalculoService.notaMaxima(estudiante.getNotas());
        boolean aprobado = CalculoService.aprobado(promedio);

// Mostrar resultados
        StringBuilder sb = new StringBuilder();
        sb.append("<html>");
        sb.append(String.format("Promedio: %.2f", promedio));
        sb.append("<br>Nota máxima: ").append(notaMax != null ? notaMax.getValor() : "N/A");
        sb.append("<br>").append(aprobado ? "Estado: Aprobado" : "Estado: Reprobado");
        sb.append("</html>");

        lblEstadistica.setText(sb.toString());

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticaActionPerformed
        // TODO add your handling code here:
        RegistroEstudianteService servicio = new RegistroEstudianteService();

        try {
            double promedioGeneral = servicio.calcularPromedioGeneral();
            Optional<Estudiante> mejorEst = servicio.mejorEstudiante();
            long aprobados = servicio.contarAprobados();
            long reprobados = servicio.contarReprobados();
            // Mostrar en la interfaz
            StringBuilder sb = new StringBuilder();
            sb.append("<html>");
            sb.append(String.format("Promedio General: %.2f", promedioGeneral));
            sb.append("<br>Aprobados: ").append(aprobados);
            sb.append("<br>Reprobados: ").append(reprobados);
            sb.append("<br>Mejor estudiante: ").append(mejorEst.isPresent() ? mejorEst.get().getNombre() : "N/A");
            sb.append("</html>");

            lblEstadistica.setText(sb.toString());
        } catch (SQLException ex) {
            System.getLogger(RegistroEstudianteFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }//GEN-LAST:event_btnEstadisticaActionPerformed

    private void tableEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEstudiantesMouseClicked
        // TODO add your handling code here:
        filaSeleccionada = tableEstudiantes.rowAtPoint(evt.getPoint());
        txtNombre.setText(String.valueOf(tableEstudiantes.getValueAt(filaSeleccionada, 1)));
        txtEdad.setText(String.valueOf(tableEstudiantes.getValueAt(filaSeleccionada, 2)));
        txtNota1.setText(String.valueOf(tableEstudiantes.getValueAt(filaSeleccionada, 3)));
        txtNota2.setText(String.valueOf(tableEstudiantes.getValueAt(filaSeleccionada, 4)));
        txtNota3.setText(String.valueOf(tableEstudiantes.getValueAt(filaSeleccionada, 5)));
    }//GEN-LAST:event_tableEstudiantesMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt((String) tableEstudiantes.getValueAt(filaSeleccionada, 0));
        int opcion = JOptionPane.showConfirmDialog(rootPane, "Desea eliminar este estudiante?", "Eliminar", JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            try {
                RegistroEstudianteService.eliminarEstudiante(id);
                actualizarListaEstudiantes();
            } catch (SQLException ex) {
                System.getLogger(RegistroEstudianteFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(rootPane, "Deseas actualizar usuario?", "Actualizar", JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            String id = String.valueOf(tableEstudiantes.getValueAt(filaSeleccionada, 0));
            String nombre = txtNombre.getText();
            int edad = Integer.parseInt(txtEdad.getText());
            List<Nota> notas = obtenerNotasDesdeCampos();
            Estudiante estudiante = new Estudiante(id, nombre, edad, notas);
            try {
                RegistroEstudianteService.actualizarEstudiante(estudiante);
                actualizarListaEstudiantes();
            } catch (SQLException ex) {
                System.getLogger(RegistroEstudianteFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new RegistroEstudianteFrame().setVisible(true);
            } catch (SQLException ex) {
                System.getLogger(RegistroEstudianteFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCargarCSV;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEstadistica;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarCSV;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstadistica;
    private javax.swing.JTable tableEstudiantes;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNota1;
    private javax.swing.JTextField txtNota2;
    private javax.swing.JTextField txtNota3;
    // End of variables declaration//GEN-END:variables
}
